name: build-misc

on:
    workflow_dispatch:

env:
    SQLITE_VERSION: "3.45.0"

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                    - os: windows-latest
                    - os: macos-latest

        steps:
            - uses: actions/checkout@v2

            - name: Download SQLite sources
              shell: bash
              run: |
                  make prepare-misc
                  make download-misc

            - name: Build for Linux
              if: matrix.os == 'ubuntu-latest'
              run: |
                  make compile-linux-misc
                  zip --junk-paths dist/misc-linux-x86.zip dist/misc/*

            - name: Build for Windows
              if: matrix.os == 'windows-latest'
              shell: bash
              run: |
                  make compile-windows-misc
                  zip --junk-paths dist/misc-win-x64.zip dist/misc/*

            - name: Build for macOS
              if: matrix.os == 'macos-latest'
              run: |
                  make compile-macos-misc
                  zip --junk-paths dist/misc-macos.zip dist/misc/*

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/*.zip
                  file_glob: true
                  overwrite: true
                  tag: ${{ env.SQLITE_VERSION }}
