name: build

on:
    push:
        branches: [incubator]
        paths:
            - .github/workflows/build.yml
            - src/**
            - test/**
            - Makefile
    pull_request:
        branches: [incubator]
    workflow_dispatch:

env:
    SQLEAN_NAME: "array"
    SQLEAN_SOURCE: "src/array/*.c"

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                    - os: windows-latest
                    - os: macos-latest

        steps:
            - uses: actions/checkout@v4

            - name: Download SQLite sources
              shell: bash
              run: |
                  make prepare-dist
                  make download-sqlite
                  make download-external

            - name: Build for Linux
              if: matrix.os == 'ubuntu-latest'
              run: |
                  make compile-linux-extension name=${{ env.SQLEAN_NAME }} src=${{ env.SQLEAN_SOURCE }}
                  make test suite=${{ env.SQLEAN_NAME }}

            - name: Build for Windows
              if: matrix.os == 'windows-latest'
              shell: bash
              run: make compile-windows-extension name=${{ env.SQLEAN_NAME }} src=${{ env.SQLEAN_SOURCE }}

            - name: Build for macOS
              if: matrix.os == 'macos-latest'
              run: make compile-macos-extension name=${{ env.SQLEAN_NAME }} src=${{ env.SQLEAN_SOURCE }}

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/${{ env.SQLEAN_NAME }}.*
                  file_glob: true
                  overwrite: true
                  tag: incubator
